In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
import pickle

In [2]:
data = pd.read_csv('Churn_Modelling.csv')
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [ ]:
#Preprocessing
data = data.drop(['RowNumber', 'CustomerId', 'Surname'],axis=1)

In [4]:
#Label encoder for Gender
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [6]:
#One Hot Encoding for Geography
OHE_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = OHE_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=OHE_geo.get_feature_names_out(['Geography']))
geo_encoded_df.head()

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0

In [8]:
data = pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [9]:
X = data.drop('EstimatedSalary',axis=1)
y = data['EstimatedSalary']

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [11]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [18]:
with open('label_encoder_gender_reg.pkl', 'wb') as f:
    pickle.dump(label_encoder_gender, f)

with open('one_hot_encoder_geo_reg.pkl', 'wb') as f:
    pickle.dump(OHE_geo, f)

with open('scaler_reg.pkl', 'wb') as f:
    pickle.dump(scaler, f)

#ANN Regression

In [12]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [15]:
#Build the model
model = Sequential([
    Dense(62, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)
])

#Compile the model
model.compile(optimizer='adam', loss='mean_absolute_error',metrics=['mae'])

model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 62)             │           806 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 32)             │         2,016 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,855 (11.15 KB)

 Trainable params: 2,855 (11.15 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

es = EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tb = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [17]:
history = model.fit(X_train_scaled, y_train,
                    validation_data=(X_test_scaled, y_test),
                    epochs=100,
                    callbacks=[es,tb])

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - loss: 100384.9688 - mae: 100384.9688 - val_loss: 98544.9609 - val_mae: 98544.9609
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 99729.5078 - mae: 99729.5078 - val_loss: 97216.0078 - val_mae: 97216.0078
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 97411.4609 - mae: 97411.4609 - val_loss: 93805.0625 - val_mae: 93805.0625
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 92777.0781 - mae: 92777.0781 - val_loss: 87961.8906 - val_mae: 87961.8906
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 85886.9766 - mae: 85886.9766 - val_loss: 80274.5078 - val_mae: 80274.5078
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 77526.4531 - mae: 77526.4531 - val_loss: 71847.9219 - val_mae: 71847.9219
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 69038.3828 - mae: 69038.3828 - val_loss: 64091.1055 - val_mae: 64091.1055
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 61677.5742 - mae: 61677.5742 - val_loss: 57977.4023 - val_mae: 57977.4023
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56277.2461 - mae: 56277.2461 - val_loss: 53884.5195 - val_mae: 53884.5195
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 53012.9805 - mae: 53012.9805 - val_loss: 51840.4258 - val_mae: 51840.4258
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 51428.8906 - mae: 51428.8906 - val_loss: 51051.6680 - val_mae: 51051.6680
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50717.2656 - mae: 50717.2656 - val_loss: 50750.0234 - val_mae: 50750.0234
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 50423.4336 - mae: 50423.4336 - val_loss: 50649.4453 - val_mae: 50649.4453
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 50289.2344 - mae: 50289.2344 - val_loss: 50604.7930 - val_mae: 50604.7930
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 50216.8945 - mae: 50216.8945 - val_loss: 50573.0234 - val_mae: 50573.0234
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 50154.2305 - mae: 50154.2305 - val_loss: 50545.8984 - val_mae: 50545.8984
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 50105.1211 - mae: 50105.1211 - val_loss: 50522.4727 - val_mae: 50522.4727
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 50059.2656 - mae: 50059.2656 - val_loss: 50485.1445 - val_mae: 50485.1445
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50022.0156 - mae: 50022.0156 - val_loss: 50460.6445 - val_mae: 50460.6445
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49985.7109 - mae: 49985.7109 - val_loss: 50442.8906 - val_mae: 50442.8906
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49956.6094 - mae: 49956.6094 - val_loss: 50417.0156 - val_mae: 50417.0156
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49928.8008 - mae: 49928.8008 - val_loss: 50403.3867 - val_mae: 50403.3867
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49904.1523 - mae: 49904.1523 - val_loss: 50392.8516 - val_mae: 50392.8516
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49880.1719 - mae: 49880.1719 - val_loss: 50385.4688 - val_mae: 50385.4688
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49860.9258 - mae: 49860.9258 - val_loss: 50371.4258 - val_mae: 50371.4258
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49838.5117 - mae: 49838.5117 - val_loss: 50356.6797 - val_mae: 50356.6797
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49816.1406 - mae: 49816.1406 - val_loss: 50351.0781 - val_mae: 50351.0781
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49800.0469 - mae: 49800.0469 - val_loss: 50335.2148 - val_mae: 50335.2148
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49782.4492 - mae: 49782.4492 - val_loss: 50330.3281 - val_mae: 50330.3281
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49770.3594 - mae: 49770.3594 - val_loss: 50312.7617 - val_mae: 50312.7617
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49752.5195 - mae: 49752.5195 - val_loss: 50312.4844 - val_mae: 50312.4844
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 49735.8477 - mae: 49735.8477 - val_loss: 50310.7617 - val_mae: 50310.7617
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49722.3320 - mae: 49722.3320 - val_loss: 50300.8398 - val_mae: 50300.8398
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49711.2656 - mae: 49711.2656 - val_loss: 50300.0547 - val_mae: 50300.0547
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49697.2891 - mae: 49697.2891 - val_loss: 50304.8516 - val_mae: 50304.8516
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49681.0547 - mae: 49681.0547 - val_loss: 50310.7930 - val_mae: 50310.7930
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 49670.2109 - mae: 49670.2109 - val_loss: 50301.6953 - val_mae: 50301.6953
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49660.2031 - mae: 49660.2031 - val_loss: 50304.4844 - val_mae: 50304.4844
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49651.0938 - mae: 49651.0938 - val_loss: 50305.3516 - val_mae: 50305.3516
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49638.4570 - mae: 49638.4570 - val_loss: 50307.6094 - val_mae: 50307.6094
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49632.6406 - mae: 49632.6406 - val_loss: 50306.9023 - val_mae: 50306.9023
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49617.1641 - mae: 49617.1641 - val_loss: 50301.5039 - val_mae: 50301.5039
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49607.6406 - mae: 49607.6406 - val_loss: 50302.8477 - val_mae: 50302.8477
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49598.9766 - mae: 49598.9766 - val_loss: 50297.1992 - val_mae: 50297.1992
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49590.4570 - mae: 49590.4570 - val_loss: 50276.4883 - val_mae: 50276.4883
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49582.0430 - mae: 49582.0430 - val_loss: 50282.4688 - val_mae: 50282.4688
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49573.3789 - mae: 49573.3789 - val_loss: 50280.7930 - val_mae: 50280.7930
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49566.7812 - mae: 49566.7812 - val_loss: 50288.9961 - val_mae: 50288.9961
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 49557.5547 - mae: 49557.5547 - val_loss: 50285.7656 - val_mae: 50285.7656
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49547.0586 - mae: 49547.0586 - val_loss: 50280.9844 - val_mae: 50280.9844
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49541.0430 - mae: 49541.0430 - val_loss: 50288.9531 - val_mae: 50288.9531
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49533.1016 - mae: 49533.1016 - val_loss: 50291.8242 - val_mae: 50291.8242
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49528.3438 - mae: 49528.3438 - val_loss: 50280.5625 - val_mae: 50280.5625
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49522.4883 - mae: 49522.4883 - val_loss: 50277.7031 - val_mae: 50277.7031
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49511.5625 - mae: 49511.5625 - val_loss: 50293.5312 - val_mae: 50293.5312

In [19]:
test_loss, test_mae = model.evaluate(X_test_scaled, y_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 50276.4883 - mae: 50276.4883

In [20]:
print(f'Test Loss: {test_loss}, Test MAE: {test_mae}')

Test Loss: 50276.48828125, Test MAE: 50276.48828125

In [21]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.